apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-deployment
  labels:
    name: cap-deployment
    app: cap
spec:
  replicas: 3
  selector:
    matchLabels:
      name: cap-pod
      app: cap
  template:
    metadata:
      labels:
        name: cap-pod
        app: cap
    spec:
      containers:
        - name: cap
          image: druva28/cap-backend:v0.0.1
          ports:
            - containerPort: 8080
