apiVersion: v1
kind: Service
metadata:
  name: cap-service
  labels:
    name: cap-service
    app: cap
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    name: cap-pod
    app: cap
